(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 300,
	height: 300,
	fps: 27,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/bg_full.jpg", id:"bg_full"},
		{src:"images/tower.jpg", id:"tower"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.bg_full = function() {
	this.initialize(img.bg_full);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1067,600);


(lib.tower = function() {
	this.initialize(img.tower);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,74,185);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgjSAZEMAAAgyHMBGlAAAMAAAAyHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-225.9,-160.5,452,321);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("A3aXbMAAAgu1MAu2AAAMAAAAu1g");
	this.shape.setTransform(30,-50);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F6E163").s().p("Ah+CmQgDgCABgKIAAi/IAAgoIAAgZIAAgPIgBgLQAAgKgDgGQgFgGgKgCIgHgBIgHAAIgCgBIgBgCQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAGgBIATAAIATABIAJAAIAJAAIAQgBIAQAAIAFABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCABIgEAAIgGABQgIACgDAFQgEAGgBALIAAAgIgBBGIAABxQAAABABAAQAAABAAAAQAAABAAAAQABAAAAAAIADgBIA8hHIBAhPIBOhjQAEgHAEACQADACgBAKIAAAjIAAAiIAAAvIAABIIAAA2QABAXABAOQAAAJAEAGQAEAGAIACIALABIAJABIACAAIABACQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgFAAIgXAAIgUgBIgJAAIgJABIgQAAIgQAAIgFAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIABgCIADAAIAGgBIAHgBQAFgCADgGQADgGAAgJQACgOAAgXIABg2IAAh4QAAgEgCgBQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQgqAxgoAvQgnAygnAzIgjAtIgGAHQgDAFgDAAIgCAAg");
	this.shape.setTransform(308.3,-1.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F6E163").s().p("Ah9CmQgEgCACgKIAAi/IgBgoIAAgZIAAgPIgBgLQAAgKgEgGQgDgGgLgCIgGgBIgIAAIgCgBIgBgCQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAEgBIAUAAIATABIAJAAIAJAAIAQgBIAQAAIAFABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgDABIgEAAIgGABQgJACgDAFQgDAGAAALIgBAgIgBBGIAABxQAAABABAAQAAABAAAAQAAABAAAAQABAAAAAAIADgBIA8hHIBAhPIBOhjQAEgHAEACQADACgBAKIAAAjIAAAiIAAAvIAABIIAAA2QAAAXACAOQAAAJAEAGQADAGAKACIAKABIAJABIACAAIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAIgFAAIgXAAIgTgBIgJAAIgJABIgRAAIgQAAIgEAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIABgCIADAAIAHgBIAFgBQAGgCADgGQACgGACgJQABgOABgXIAAg2IAAh4QAAgEgBgBQgBAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQgqAxgpAvQgmAygoAzIgjAtIgEAHQgEAFgDAAIgBAAg");
	this.shape_1.setTransform(268.1,-1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F6E163").s().p("ACaCvIAAgFIAAgDIAAgCIgBgMQgBgHgIgEQgGgEgRAAIgKAAIgKAAIgLAAIgTABIiXAAIgYgBIgMAAIgJAAIgQABIgPAAIgGgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIABgCIADAAIAGgBIAHgCQAFgBADgGQADgGABgJIABglIABg2IAAhJIAAgoIAAgZIgBgOIAAgMQAAgJgEgGQgEgGgKgCIgHgBIgHAAIgDgBIgBgCQAAAAABgBQAAAAAAgBQAAAAAAAAQABAAAAgBIAFAAIAUAAIASAAIAJABIAJgBIARAAIAQAAIAEAAQABABAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAIgCABIgEAAIgHABQgIACgDAFQgDAGgBAKIgBANIAAAXIAAAuIAABSIAAA2QAAAXACAOIABAIIADAGQArADArAAQApAAArgDIACgGIABgIQABgOABgXIABg2IAAhJIAAgoIAAgZIgBgOIAAgMQgBgJgEgGQgEgGgJgCIgHgBIgIAAIgCgBIgBgCQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABgBIAEAAIAVAAIASAAIAJABIAJgBIAQAAIAQAAIAFAAQAAABABAAQAAAAAAAAQAAABAAAAQABABAAAAIgBACIgCABIgFAAIgGABQgJACgDAFQgDAGAAAKIgBAMIAAAOIAAAZIAAAoIAABJIAAAsIABAhQgBARAGAGQAGAFAGgBIAKgBQAJAAAGgCIAHAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAAEIgDARIgEATIgCANIgCADQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBg");
	this.shape_2.setTransform(228.5,0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F6E163").s().p("Ah+CmQgDgCABgKIAAi/IAAgoIAAgZIAAgPIgBgLQAAgKgDgGQgFgGgKgCIgHgBIgHAAIgCgBIgBgCQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAGgBIATAAIATABIAJAAIAJAAIAQgBIAQAAIAFABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCABIgEAAIgGABQgIACgDAFQgEAGgBALIAAAgIgBBGIAABxQAAABABAAQAAABAAAAQAAABAAAAQABAAAAAAIADgBIA8hHIBAhPIBOhjQAEgHAEACQADACgBAKIAAAjIAAAiIAAAvIAABIIAAA2QABAXABAOQAAAJAEAGQAEAGAIACIALABIAJABIACAAIABACQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgFAAIgXAAIgUgBIgJAAIgJABIgQAAIgQAAIgFAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIABgCIADAAIAGgBIAHgBQAFgCADgGQADgGAAgJQACgOAAgXIABg2IAAh4QAAgEgCgBQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQgqAxgoAvQgnAygnAzIgjAtIgGAHQgDAFgDAAIgCAAg");
	this.shape_3.setTransform(187.7,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F6E163").s().p("ACeC0IAAgGIAAgFQAAgGgCgGQgBgGgJgEQgHgEgSAAIj1AAQgQAAgIADQgIADgCAHIgBAJIgBAMIAAADIgCABIgDgBIgBgDIgCgLIgDgQIgDgPIgBgIIABgFIAAgBIAIACQAGADAIAAQAQAAAIgIQAIgIAFgOIBnkEIAGgNQAAgBABAAQAAgBABAAQAAgBABAAQAAAAAAAAQACAAABADIAGAMIBmD9QAHARALAKQAKAKANAAQAJAAAGgBIAJgCIACABIAAACIgBAIIgDAQIgEARIgCAKIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAgAgPhvIhJDPIgFAQIgCAOIAbABIAdABIAbAAIAvgBIAygBIhbjuIgCgDIgDgBQgDAAgBAFg");
	this.shape_4.setTransform(149.7,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F6E163").s().p("ACJChIgXAAIgdAAIgJgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAIABgCIADgBIACgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAIAAgDIgBgDIgnhnIgCgCIgCAAIhYAAIgCAAIgCADIgZBKQgDAIgCAIQgCAHAAAFQABAHAFADQAFADAGAAIAEAAIADAAIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIgGAAIgLAAIgNgBIgIAAIgKABIgSAAIgUAAIgFAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIABgCIAEAAIAFgBIAGAAQAOgCAJgLQAHgLAGgQIBfkDIAFgNQADgDACAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAFAMIAHAUIAPAnIATAyIAVA0IAUAzIAQAoQAHASAGAKQAHAJAFAEQAGAEAFABIAJACIAHABIAEAAIABACQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBABIgGAAIgOAAgAgLhfIgBADIgmBwIAAACIACAAIBOAAIACAAIAAgCIgnhwIgBgEIgCgBIgBACg");
	this.shape_5.setTransform(116.2,-1.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F6E163").s().p("AgUCeIgTgBIgKAAIgHAAIgRABIgPAAIgGgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIABgCIADAAIAGgBIAGgCQAGgBADgGQADgGABgJIACglIAAg2IAAhJIAAgoIAAgZIAAgOIgBgMQAAgJgEgGQgEgGgKgCIgHgBIgHAAIgCgBIgBgCQAAAAAAgBQAAAAAAgBQAAAAAAAAQABAAAAgBIAFAAIAUAAIASAAIAKABIANgBIATAAIASAAQAaAAAQAEQARAFAIAGQAJAGACADQAIAHAHANQAGANAAAQQAAAfgNAWQgNAWgXALQgYAMgdAAIgDAAIgFAAIgDgBIgBgCQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAJgBQATAAAQgHQARgIAJgQQAKgPAAgUQAAgHgBgLQgCgKgFgNQgFgMgLgLQgLgLgLgFQgMgFgJgBIgMAAIgKABIgIACQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABIgBAFIAACrIAAA2QABAXACAOQAAAJADAGQADAGAKABIAKACIAHABIADAAIAAACQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAIgGABIgVAAg");
	this.shape_6.setTransform(88.7,-1.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F6E163").s().p("AAfChIgTgBIgKAAIgGAAIgRABIgQAAIgFgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgCIADAAIAGgBIAGgCQAHgBACgGQADgGABgJQABgOABgXIAAg2IAAiwIg+AAQgTABgKACQgKAEgEAHIgFAIIgCAFIgCADQgBABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgBgBIgBgDIACgIIADgNIADgPIACgHIABgFQABgBAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAGACQAEACAIABIATABIAOABICcAAQAUAAAJgCIANgCIABACIABADIgBAQIAAATIgBALIAAAFIgDABQAAAAAAgBQgBAAAAAAQAAAAAAAAQgBgBAAAAIgBgGIAAgEQgBgGgFgGQgEgFgLgDQgLgDgUgBIg1AAIAACwIAAA2QABAXABAOQABAJADAGQADAGAJABIALACIAIABIADAAIABACQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgFABIgXAAg");
	this.shape_7.setTransform(60,-1.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F6E163").s().p("ABAChIg0gBIgfgBIgSgBIgOAAIgPABIgNAAIgFAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIABgCIADAAIAGgBIAGgBQAFgBADgEIAEgNQACgJAAgYIABg/IAAhIIAAg3IgBgcIgBgNQAAgHgDgFQgEgFgKgCIgHgBIgHAAIgCgBIgBgCQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAFgBIAUAAIATABIAJAAIApAAIAiAAIARgBIALgBIAIAAIADgCIADgBIABACIABADIgBAGIgCAOIAAAHIgBAMIgBAIIgCADIgCABIgCgBIAAgDIgBgHIgEgJQgBgFgJgEQgIgFgTAAIgHAAIgPgBIgOAAIgKAAIgCAAIgBAEIAABzIABAEIACABIALAAIASgBIAWAAIANAAIANgCQAFgBACgDIAEgEIACgCIACABIAAADIgBAJIgCARIgBAWIgBAGQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgCgBIgBgDIAAgGIgBgIQgBgEgFgEQgEgFgMgBIgNAAIgTAAIgPAAIgLAAIgCAAIgBABIAABsQAAAOAEAIQADAHALADQAJADAUAAIAUgBQAMAAAIgEQAIgDAFgHQAEgHACgNIACgFQAAAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAEIgBAKIgBARIgDAOQgCAIgEABQgEACgIAAIgFAAg");
	this.shape_8.setTransform(19.7,-1.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F6E163").s().p("AhSCeIgSgBIgRAAIgJgBIgJABIgQAAIgQAAIgFAAQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAgCIADAAIAGgBIAHgBQAGgCACgGQACgGACgJQABgOAAgXIAAg2IAAhIIAAgmIAAgWIAAgPIAAgQQgBgKgEgGQgEgGgIgBIgHgCIgFAAIgDgBIgBgCQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAFgBIAQAAIASABIAIAAIAJAAIARgBIAPAAIAFABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIgBACIgCABIgFAAIgFABQgJACgEAFQgDAGAAALIAABkIAAADIACACIAIABIASAAIAOAAQAcAAAYALQAWAKAOASQAOAVAAAcQABAXgMAVQgNAVgVANQgYANgkABIgMgBgAhqgEQgFAEACAGIAAAKIAAAaIAAAdIAAAXIAAAMQAAAPACAHQACAHAKAEQAGADAHABIANACIALAAQAMAAANgFQAOgFAKgNQAJgNAAgYQAAgOgDgQQgEgQgLgPQgKgOgRgJQgRgIgXAAIgEAAQgNAAgEADgACUCdIgTgBIgJAAIgJABIgRAAIgQAAIgFAAQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAgBIABgCIADAAIAGgBIAGgBQAGgCADgGQADgGAAgJQACgOABgXIAAg2IAAhIIAAgoIAAgZIAAgPIgBgLQAAgKgEgGQgEgGgGgBIgIgCIgGAAIgCgBIgBgCQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAFgBIARAAIARABIAJAAIAIAAIARgBIAPAAIAGABQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIgBACIgCABIgEAAIgHABQgIACgDAFQgEAGAAALIAAALIgBAPIAAAZIAAAoIAABIIAAA2QAAAXACAOQAAAJAEAGQADAGAKACIAKABIAJABIACAAIABACQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABIgFAAIgXAAg");
	this.shape_9.setTransform(-13.7,-1.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F6E163").s().p("ACHCeIgUgBIgJAAIgJAAIgQABIgQAAIgFgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgCIADAAIAGgBIAHgCQAFgBADgGQACgGABgJQACgOAAgXIABg2IAAgmIgBgCIgCgBIiwAAIgCABIAAACIAAAmIAAA2QAAAXABAOQABAJAEAGQADAGAJABIAKACIAJABIACAAIABACQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgFABIgYAAIgTgBIgJAAIgJAAIgRABIgPAAIgFgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgCIACAAIAHgBIAGgCQAGgBACgGQAEgGABgJIABglIAAg2IAAhJIAAgoIAAgYIAAgPIAAgLQgBgLgEgFQgDgGgKgCIgIgBIgHAAIgCgBIgBgCQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAAAgBIAGAAIAUAAIASAAIAJABIAJgBIARAAIAPAAIAFAAQABABAAAAQAAAAABAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgBABIgFAAIgGABQgIACgEAFQgDAGgBALIAAAQIAAAcIAAAzIAAAJIAAACIACAAICwAAIACAAIABgCIAAgJIAAgzIgBgcIAAgQQgBgLgDgFQgEgGgKgCIgHgBIgHAAIgDgBIgBgCQAAAAABgBQAAAAAAgBQAAAAAAAAQABAAAAgBIAFAAIAUAAIASAAIAJABIAJgBIARAAIAQAAIAEAAQABABAAAAQAAAAABAAQAAABAAAAQAAABAAAAIgBACIgCABIgEAAIgHABQgIACgDAFQgDAGgBALIgBALIAAAPIAAAYIAAAoIAABJIAAA2QABAXABAOQABAJADAGQAEAGAIABIAKACIAJABIADAAIABACQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgFABIgXAAg");
	this.shape_10.setTransform(-55.5,-1.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F6E163").s().p("ACeC0IAAgGIAAgFQABgGgDgGQgCgGgHgEQgJgEgRAAIj1AAQgQAAgIADQgJADgBAHIgBAJIgBAMIAAADIgDABIgCgBIgBgDIgCgLIgDgQIgDgPIgBgIIABgFIAAgBIAIACQAFADAJAAQAQAAAIgIQAIgIAFgOIBnkEIAGgNQAAgBABAAQAAgBABAAQAAgBABAAQAAAAAAAAQACAAABADIAGAMIBmD9QAHARALAKQAJAKAOAAQAJAAAHgBIAJgCIABABIAAACIgBAIIgDAQIgEARIgCAKIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAgAgPhvIhJDPIgFAQIgBAOIAaABIAdABIAbAAIAvgBIAygBIhbjuIgDgDIgCgBQgCAAgCAFg");
	this.shape_11.setTransform(-93.5,0);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F6E163").s().p("AhLCVQgfgPgUgYQgTgYgKgdQgJgdAAgcQAAgZAKgdQAJgcAUgYQAVgZAfgQQAfgQAqAAQAvAAAlATQAlATAWAjQAVAkABAxQgBAhgLAfQgMAfgWAXQgWAYgfANQgfAOgkAAQgrAAgfgPgAhAiFQgcAPgQAfQgQAfAAAtQABAwARAkQASAjAeAVQAeATAkAAQAPAAATgFQAUgFATgQQASgPANgdQAMgdAAgtQAAgjgKgdQgLgdgSgUQgSgUgWgKQgXgKgXAAQgkAAgbAQg");
	this.shape_12.setTransform(-131.7,-1.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F6E163").s().p("AgUCeIgTgBIgJAAIgIAAIgRABIgQAAIgEgBQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIACgCIACAAIAHgBIAFgCQAGgBADgGQADgGABgJIACglIAAg2IAAhJIAAgoIAAgZIAAgOIgBgMQgBgJgDgGQgEgGgKgCIgHgBIgIAAIgBgBIgBgCQAAAAAAgBQAAAAAAgBQAAAAAAAAQABAAAAgBIAFAAIAUAAIASAAIAKABIANgBIATAAIATAAQAaAAAPAEQARAFAIAGQAIAGADADQAHAHAIANQAGANABAQQgBAfgNAWQgNAWgYALQgXAMgdAAIgDAAIgFAAIgDgBIgBgCQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAJgBQASAAARgHQARgIAJgQQAJgPAAgUQABgHgBgLQgCgKgFgNQgFgMgLgLQgLgLgLgFQgMgFgJgBIgNAAIgJABIgJACQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABIAAAFIAACrIAAA2QAAAXACAOQAAAJADAGQAEAGAJABIAKACIAHABIACAAIABACQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgFABIgVAAg");
	this.shape_13.setTransform(-163.6,-1.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F6E163").s().p("AhLCVQgfgPgUgYQgTgYgKgdQgJgdAAgcQAAgZAKgdQAJgcAUgYQAVgZAfgQQAfgQAqAAQAvAAAlATQAlATAWAjQAVAkABAxQgBAhgLAfQgMAfgWAXQgWAYgfANQgfAOgkAAQgrAAgfgPgAhAiFQgcAPgQAfQgQAfAAAtQABAwARAkQASAjAeAVQAeATAkAAQAPAAATgFQAUgFATgQQASgPANgdQAMgdAAgtQAAgjgKgdQgLgdgSgUQgSgUgWgKQgXgKgXAAQgkAAgbAQg");
	this.shape_14.setTransform(-196.9,-1.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F6E163").s().p("AgKCgIgTgBIgJAAIgJAAIgPABIgQAAIgFgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgCIADAAIAGgBIAHgCQAEgBADgDQACgFACgJIACggIABg/IAAhJIAAg2IgBgdIAAgMQgBgIgDgEQgEgFgKgCIgHgBIgHAAIgDgBIgBgCQAAAAAAgBQABAAAAgBQAAAAAAAAQABAAAAgBIAFAAIAUAAIATAAIAJABIANAAIAXAAIAcgBIAZAAIAMAAIALgBIAHAAIAEgCIACgBQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIABACIgBAHIgDANIAAAIIgBALIgBAJIgBADIgCABIgCgBIgBgEIgBgHIgDgJQgBgEgJgFQgJgEgSAAIg4gBIgCABIgBADIAACtIAAAnIAAAiIACAWQABAIAEAFQAEAFAHAAIAIACIAJABIADAAIAAACQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIgFABIgWAAg");
	this.shape_15.setTransform(-227.8,-1.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F6E163").s().p("ACJChIgXAAIgdAAIgJgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAIABgCIACgBIADgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAIAAgDIgBgDIgnhnIgCgCIgBAAIhZAAIgCAAIgCADIgZBKQgEAIgBAIQgBAHAAAFQAAAHAFADQAFADAGAAIAEAAIADAAIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBABIgEAAIgMAAIgNgBIgIAAIgKABIgSAAIgUAAIgGAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIABgCIAEAAIAFgBIAHAAQAOgCAHgLQAJgLAFgQIBfkDIAFgNQABgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAEAMIAIAUIAPAnIATAyIAVA0IAUAzIAPAoQAIASAHAKQAGAJAFAEQAGAEAEABIAJACIAIABIAEAAIABACQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBABIgGAAIgOAAgAgLhfIgCADIglBwIAAACIABAAIBPAAIABAAIAAgCIgmhwIgBgEIgCgBIgBACg");
	this.shape_16.setTransform(-255.2,-1.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F6E163").s().p("ACKChIgYAAIgdAAIgJgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAAAIACgCIACgBQAAgBAAAAQABAAAAgBQABAAAAgBQABAAAAgBQABgCgCgGIgnhnIgHgUIgnhwQgDgJgCAJIglBwIgiBfQgCAIgBAIQgDAHAAAFQABAHAFADQAFADAFAAIAFAAIADAAIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIgGAAIgLAAIgMgBIgJAAIgKABIgRAAIgVAAIgFAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIABgCIACAAIAHgBIAFAAQAOgCAJgLQAHgLAGgQIBfkDIAFgNQADgDACAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAFAMIAHAUIAPAnIATAyIAVA0IAUAzIAQAoQAHASAGAKQAHAJAGAEQAFAEAFABIAJACIAIABIACAAIABACQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBABIgGAAIgNAAg");
	this.shape_17.setTransform(-284.5,-1.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F6E163").s().p("AgJCgIgSgBIgRAAIgJgBIgJABIgQAAIgQAAIgFAAQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIABgCIADAAIAGgBIAGgBQAFgBACgEQADgEACgJIACghIAAg/IAAhIIAAg3IAAgcIgBgNQAAgHgEgFQgDgFgKgCIgHgBIgIAAIgCgBIgBgCQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAFgBIAbABIAYAAIARAAIAaAAIAbAAIAZAAIAMgBIAMgBIAHAAIADgCIADgBQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIABADIgCAGIgCAOIgBAIIAAALIgBAIIgBADIgCACQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIAAgDIgBgHIgDgJQgCgFgJgEQgIgFgTAAIhBgBIgDABIgBADIAABuIABAEIAEABIAJABIAPAAQAPAAAUADQAUAEATAJQASAIAMARQAMASAAAdQAAAXgMAVQgMAVgXANQgYANgkABIgKgBgAgkgGQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABjQAAAQABAJQABAJADAEQADAFAHADQAGADAHABIALACIALAAQAMAAANgFQAOgFAKgNQAKgNAAgXQAAgNgDgQQgEgPgJgPQgJgPgQgLQgMgGgLgCQgIgDgMAAIgRAAQgGABgBABg");
	this.shape_18.setTransform(-313.5,-1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-330.2,-27.3,660.4,54.4);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFBCQgMgFgIgJQgIgKgEgNQgEgNAAgPIgfAAIAABFIgJAAIAAiLIAJAAIAAA/IAgAAQABgOAFgMQAEgMAIgJQAIgIAMgFQAJgFAPAAQAOAAALAGQALAEAIAKQAIAJAEANQAEANAAAQQAAAQgEAOQgFAOgJAJQgIAJgLAGQgMAEgNAAQgQAAgJgGgAAAg6QgJAFgHAIQgHAIgEAMQgEAMAAANQAAAPAEALQAEAMAHAIQAGAIAKAFQAHAEAMAAQAMAAAKgEQAJgEAHgIQAHgIAEgMQAEgMAAgPQAAgOgDgMQgEgMgHgIQgHgIgKgEQgJgEgMAAQgLAAgJAEg");
	this.shape.setTransform(130.5,12.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnBGIAAiLIAKAAIAAA+IAeAAQAIABAHACQAHACAGACQAFAFADAHQADAHAAAKQAAAIgDAIQgDAHgFAFQgFAGgIADQgIAEgIAAgAgdA9IAbAAQAHAAAGgCQAHgDAEgEQAEgEACgGQACgGAAgGQAAgIgCgFQgDgGgEgDQgEgEgHgCQgGgBgHgBIgaAAg");
	this.shape_1.setTransform(115.5,12.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAlAAQAOABAKAIQAKAJAAAPQAAAMgHAJQgGAJgMAEIAAAAQAPABAIAIQAIAIAAAOQAAASgLAMQgMAKgRABgAgdA9IAaAAQAPAAAJgIQAIgIAAgPQAAgdglAAIgVAAgAgdgGIAUAAQANABAJgJQAKgHAAgOQAAgZgcAAIgYAAg");
	this.shape_2.setTransform(104.8,12.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfASgVQATgUAdAAQAcAAASATQARAUAAAgQAAAggSAUQgSAUgdAAQgcAAgSgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgPgQQgOgRgaAAQgXAAgPASg");
	this.shape_3.setTransform(91.8,12.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAiAAQAUABAMAJQAKAKABAUQAAATgNALQgNANgUAAIgVAAIAAA4gAgcAFIAUAAQARgBAKgGQAKgKAAgQQgBgfghgBIgXAAg");
	this.shape_4.setTransform(79.3,12.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfATgVQARgUAdAAQAdAAARATQASAUAAAgQAAAggSAUQgSAUgdAAQgdAAgRgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgOgQQgPgRgaAAQgXAAgPASg");
	this.shape_5.setTransform(66.3,12.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA2BYIAAglIhrAAIAAAlIgJAAIAAguIALAAIANgfQAHgOAFgRQAFgRADgRQADgSABgPIA6AAIAACBIAUAAIAAAugAgHg9IgEAVIgFAVIgHAUIgJAVIgJAUIBMAAIAAh4IgoAAIgCARg");
	this.shape_6.setTransform(52.4,14.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaBGQgIgDgHgFIAAgKIAIAFIAKAEIAKACIAJAAQAHABAHgDQAIgDAFgEQAEgEADgFQACgGABgGQAAgIgDgHQgDgFgGgFQgFgDgJgCQgHgCgJAAIgMAAIAAgHIAJAAQAKAAAFgCQAIgBAEgFQAGgEADgFQADgGgBgHQABgFgCgFQgCgGgEgDQgEgEgFgCQgGgBgFAAQgJgBgIADQgIADgHAEIAAgJIAHgDIAIgDIAIgCIAKgBQAHAAAHACQAHADAFAEQAFAFACAGQADAGAAAIQAAANgIAJQgHAJgOAEIAAABQAJAAAHABQAGAEAEAEQAFAFACAGQACAGAAAGQAAAIgDAHQgDAIgGAGQgGAFgJAEQgKADgJAAQgMAAgKgCg");
	this.shape_7.setTransform(40.7,12.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDBGIAAiCIgpAAIAAgJIBZAAIAAAJIgpAAIAACCg");
	this.shape_8.setTransform(25.3,12.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAqBGIAAhsIAAgDIAAgDIABgDIAAgEIgBAAIgBACIgBADIgCACIgCACIhRBwIgHAAIAAiLIAKAAIAABsIAAAGIgBAGIABAAIADgFIADgEIBRhvIAHAAIAACLg");
	this.shape_9.setTransform(13.4,12.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA2BYIAAglIhrAAIAAAlIgKAAIAAguIAMAAIANgfQAHgOAFgRQAFgRADgRQADgSABgPIA6AAIAACBIAUAAIAAAugAgIg9IgDAVIgGAVIgGAUIgIAVIgJAUIBKAAIAAh4IgnAAIgDARg");
	this.shape_10.setTransform(0,14.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_11.setTransform(-11.1,12.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AglBGIAAiLIAhAAQAUABALAJQAMAKgBAUQAAATgMALQgNANgUAAIgVAAIAAA4gAgcAFIAUAAQARgBAKgGQAJgKAAgQQABgfgjgBIgWAAg");
	this.shape_12.setTransform(-21.2,12.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAlAAQAOABAKAIQAKAJAAAPQAAAMgHAJQgGAJgMAEIAAAAQAPABAIAIQAIAIAAAOQAAASgLAMQgMAKgRABgAgdA9IAaAAQAPAAAJgIQAIgIAAgPQAAgdglAAIgVAAgAgdgGIAUAAQANABAJgJQAKgHAAgOQAAgZgcAAIgYAAg");
	this.shape_13.setTransform(-31.8,12.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAhBGIAAg/IgUAAQgGAAgEABQgDACgCADIgGAHIgEAJIgTApIgLAAIAVgsIAEgJIAFgGIAEgDIAFgDIAAAAIgMgEQgGgBgEgFQgFgEgDgHQgCgGAAgJIABgHQABgFACgEQACgEAEgEQADgEAFgDIALgFQAGgBAGgBIAlAAIAACLgAgHg5QgHACgEAFQgEAEgCAFIgBAKQAAAJADAGQADAGAFADQAFAEAHACQAEABAHAAIAYAAIAAg8IgaAAQgIABgGACg");
	this.shape_14.setTransform(-48.6,12.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgxBGIgEgBIAAgKQAEACAFAAQAFAAADgCQADgDADgDIAEgLIAEgOIACgLIADgOIADgPIACgSIADgUIADgUIA8AAIAACLIgKAAIAAiCIgsAAIgCAbIgEAbIgEAWIgDATIgEANQgDAHgDAGQgEAEgFAEQgFACgGAAIgGAAg");
	this.shape_15.setTransform(-60.5,12.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfASgVQASgUAeAAQAcAAASATQARAUAAAgQAAAggSAUQgSAUgdAAQgcAAgSgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgOgQQgPgRgaAAQgWAAgQASg");
	this.shape_16.setTransform(-73.5,12.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgfBGIAAiLIBAAAIAAAJIg3AAIAACCg");
	this.shape_17.setTransform(-84.4,12.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfASgVQATgUAdAAQAcAAASATQARAUAAAgQAAAggSAUQgSAUgdAAQgcAAgSgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgPgQQgOgRgaAAQgXAAgPASg");
	this.shape_18.setTransform(-96.8,12.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAdBGIg6hEIgCgCIgBAAIAABGIgJAAIAAiLIAJAAIAABDIABAAIACgEIA3g/IANAAIg8BFIA/BGg");
	this.shape_19.setTransform(-108.5,12.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgxBGIgEgBIAAgKQAEACAFAAQAFAAADgCQADgDADgDIAEgLIAEgOIACgLIADgOIADgPIACgSIADgUIADgUIA8AAIAACLIgKAAIAAiCIgsAAIgCAbIgEAbIgEAWIgDATIgEANQgDAHgDAGQgEAEgFAEQgFACgGAAIgGAAg");
	this.shape_20.setTransform(-121.5,12.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAuBGIgQgsIg7AAIgQAsIgLAAIA1iLIAHAAIA1CLgAgCguIgYA/IA0AAIgXg+IgCgHIgBgEIAAAAIgCAKg");
	this.shape_21.setTransform(-133.2,12.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_22.setTransform(125.9,-10);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAqBGIAAhsIAAgDIAAgDIABgEIAAgDIgBAAIgBACIgBADIgCADIgBABIhSBwIgGAAIAAiLIAJAAIAABsIAAAGIAAAGIAAAAIADgFIADgEIBRhvIAHAAIAACLg");
	this.shape_23.setTransform(113.9,-10);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAoBGIAAhEIhPAAIAABEIgJAAIAAiLIAJAAIAABAIBPAAIAAhAIAJAAIAACLg");
	this.shape_24.setTransform(100.3,-10);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_25.setTransform(89.1,-10);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgxBGIgEgBIAAgKQAEACAFAAQAFAAADgCQADgDADgDIAEgLIAEgOIACgLIADgOIADgPIACgTIADgTIADgUIA8AAIAACLIgKAAIAAiCIgsAAIgCAbIgEAbIgEAWIgDATIgEANQgDAHgDAGQgEAEgFAEQgFADgGAAIgGgBg");
	this.shape_26.setTransform(76.9,-9.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgnBGIAAiLIBFAAIAAAJIg7AAIAAA1IAeAAQAIABAHACQAHACAGACQAFAFADAHQADAHAAAKQAAAIgDAIQgDAHgFAFQgFAGgIADQgIAEgIAAgAgdA9IAbAAQAHAAAGgDQAHgCAEgEQAEgEACgGQACgGAAgGQAAgIgCgFQgDgGgEgDQgEgEgHgCQgGgBgHgBIgaAAg");
	this.shape_27.setTransform(66.6,-10);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_28.setTransform(56.3,-10);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAiAAQAUAAAMAKQALALgBASQAAAVgMAKQgNAMgUAAIgVAAIAAA5gAgcAEIAUAAQARAAAKgHQAKgIgBgRQABgfgigBIgXAAg");
	this.shape_29.setTransform(46.2,-10);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgDBGIAAiCIgpAAIAAgJIBZAAIAAAJIgpAAIAACCg");
	this.shape_30.setTransform(35.7,-10);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfASgVQASgUAeAAQAcAAASATQARAUAAAgQAAAggSAUQgSAUgdAAQgcAAgSgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgOgQQgPgRgaAAQgWAAgQASg");
	this.shape_31.setTransform(23.3,-10);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAoBGIAAiCIhPAAIAACCIgJAAIAAiLIBhAAIAACLg");
	this.shape_32.setTransform(9.2,-10);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgpBGIgGgCIAAgLIAHADIAHACQAFAAAFgDQAEgCADgEIAHgKIAHgNIguhkIAKAAIAkBNIAAADIACADIAAAEIAAADIABAAIADgGIACgFIAihPIAKAAIgtBlIgGAQQgEAIgFAFQgEAFgGADQgGADgHAAIgIgBg");
	this.shape_33.setTransform(-2.4,-9.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_34.setTransform(-17.7,-10);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AguA0QgSgTAAggQAAgfASgVQATgUAdAAQAcAAASATQARAUAAAgQAAAggSAUQgSAUgdAAQgcAAgSgUgAgmgsQgQARAAAbQAAAdAPARQAPARAYAAQAZAAAPgRQAPgRAAgdQAAgdgPgQQgOgRgaAAQgXAAgPASg");
	this.shape_35.setTransform(-30.2,-10);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAoBGIAAhEIhPAAIAABEIgJAAIAAiLIAJAAIAABAIBPAAIAAhAIAJAAIAACLg");
	this.shape_36.setTransform(-44.3,-10);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAjAAQATAAALAKQAMALAAASQAAAVgNAKQgNAMgVAAIgUAAIAAA5gAgcAEIAUAAQARAAAKgHQAKgIAAgRQgBgfghgBIgXAAg");
	this.shape_37.setTransform(-55.9,-10);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_38.setTransform(-66.1,-10);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AA4BGIAAhiIABgVIgBAAIgFANIgyBqIgBAAIgyhpIgEgOIgBAAIABASIAABlIgKAAIAAiLIAJAAIA0BwIACACIABADIAAAGIAAAAIACgDIADgJIAzhvIAJAAIAACLg");
	this.shape_39.setTransform(-79.4,-10);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgaBGQgIgEgHgDIAAgLIAJAFIAJAEIAKACIAJAAQAIAAAHgCQAHgDAEgEQAFgEADgFQADgHgBgFQAAgJgCgGQgDgFgGgEQgFgEgJgCQgHgCgJAAIgMAAIAAgHIAJAAQAKAAAFgBQAIgCAEgFQAGgEADgFQACgGAAgHQAAgFgBgFQgCgGgEgDQgDgDgGgDQgGgBgFAAQgJgBgIADQgIADgGAFIAAgKIAGgEIAIgCIAIgCIAKgBQAHAAAHACQAIADAEAFQAFAEACAGQADAGAAAIQAAANgHAJQgIAJgOAEIAAABQAJAAAGABQAHAEAEAEQAFAFACAGQACAGAAAGQAAAIgDAHQgEAIgFAGQgHAFgJAEQgJADgJAAQgMAAgKgCg");
	this.shape_40.setTransform(-92.7,-10);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AghBGIAAiLIBAAAIAAAJIg2AAIAAA4IAyAAIAAAHIgyAAIAAA6IA5AAIAAAJg");
	this.shape_41.setTransform(-102.7,-10);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgmBGIAAiLIAiAAQAUAAAMAKQALALgBASQAAAVgMAKQgNAMgUAAIgVAAIAAA5gAgcAEIAUAAQARAAAKgHQAKgIAAgRQAAgfgigBIgXAAg");
	this.shape_42.setTransform(-112.8,-10);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAiBGIAAhAIgWAHQgLAEgJAAQgJgBgHgCQgGgCgEgFQgFgEgCgEQgCgHAAgIIAAg1IAKAAIAAA0QAAANAGAFQAHAHANAAQAIAAALgDIAWgFIAAhFIAKAAIAACLg");
	this.shape_43.setTransform(-124.4,-10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.6,-26.6,283.3,53.2);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8151F").s().p("AAoBJIAAhjIgkBjIgIAAIgihjIAABjIgZAAIAAiRIAhAAIAeBXIAfhXIAhAAIAACRg");
	this.shape.setTransform(51.8,-0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A8151F").s().p("AgeBBQgNgKgHgRQgHgRAAgVQAAgUAHgRQAHgRANgKQANgKARAAQASAAANAKQANAKAHARQAHARAAAUQAAAVgHARQgHARgNAKQgNAKgSAAQgRAAgNgKgAgRguQgIAIgDAMQgEAMAAAOQAAAPAEAMQADAMAIAHQAIAHAJABQAKgBAIgHQAIgHADgMQAEgMAAgPQAAgOgEgMQgDgMgIgIQgIgHgKAAQgJAAgIAHg");
	this.shape_1.setTransform(37.2,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A8151F").s().p("AgtBJIAAiRIAwAAQAOAAAKAGQAJAHAFAKQAFAKAAANQAAAMgFAKQgFAJgJAGQgKAGgOAAIgYAAIAAA4gAgVgCIAVAAQAKAAAFgHQAGgGAAgLQAAgMgGgGQgFgHgKAAIgVAAg");
	this.shape_2.setTransform(25.2,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A8151F").s().p("AgnBJIAAiRIBPAAIAAAVIg2AAIAAAoIA0AAIAAAUIg0AAIAAAqIA2AAIAAAWg");
	this.shape_3.setTransform(14.2,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A8151F").s().p("AgKBJIAAh8IgiAAIAAgVIBZAAIAAAVIghAAIAAB8g");
	this.shape_4.setTransform(3.7,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A8151F").s().p("AAWBJIgkg9IgLARIAAAsIgZAAIAAiRIAZAAIAABHIArhHIAdAAIgvBFIAzBMg");
	this.shape_5.setTransform(-6.6,-0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A8151F").s().p("AAgBJIgIgdIgvAAIgHAdIgbAAIAsiRIAbAAIAsCRgAATAWIgThEIgSBEIAlAAg");
	this.shape_6.setTransform(-19.1,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#A8151F").s().p("AgtBJIAAiRIAwAAQAOAAAKAGQAJAHAFAKQAFAKAAANQAAAMgFAKQgFAJgJAGQgKAGgOAAIgYAAIAAA4gAgVgCIAVAAQAKAAAFgHQAGgGAAgLQAAgMgGgGQgFgHgKAAIgVAAg");
	this.shape_7.setTransform(-30.2,-0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#A8151F").s().p("AAgBJIgIgdIgvAAIgHAdIgbAAIAsiRIAbAAIAsCRgAATAWIgThEIgSBEIAlAAg");
	this.shape_8.setTransform(-42.2,-0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#A8151F").s().p("AAeBJIgeg4IgdA4IgcAAIArhJIgohIIAcAAIAaA1IAbg1IAcAAIgoBIIArBJg");
	this.shape_9.setTransform(-53.9,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.8,-15.4,123.6,30.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8151F").s().p("AAoBJIAAhjIgkBjIgIAAIgjhjIAABjIgYAAIAAiRIAhAAIAeBXIAfhXIAhAAIAACRg");
	this.shape.setTransform(40.4,-0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A8151F").s().p("AAaBJIAAhgIg0BgIgXAAIAAiRIAYAAIAABeIAzheIAYAAIAACRg");
	this.shape_1.setTransform(26.1,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A8151F").s().p("AAWBJIgkg9IgLARIAAAsIgZAAIAAiRIAZAAIAABHIArhHIAdAAIgvBFIAzBMg");
	this.shape_2.setTransform(14.3,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A8151F").s().p("AgYBBQgNgJgHgRQgIgRAAgWQAAgVAIgRQAHgRANgJQAOgKAQAAQANAAAJAEQAJAFAGAHQAGAIAEAIIgVAJQgDgJgHgFQgHgGgJAAQgJAAgIAHQgHAHgFAMQgEANAAAOQAAAPAEAMQAFANAHAGQAIAHAJABQAKgBAGgGQAHgGADgJIAVAJQgEAJgGAHQgGAIgJAFQgJAFgNAAQgQAAgOgKg");
	this.shape_3.setTransform(1.9,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A8151F").s().p("AA3BJIgmg9IgFAIIAAA1IgWAAIAAg1IgGgIIglA9IgdAAIAzhMIgwhFIAdAAIAoA9IAAg9IAWAAIAAA9IAng9IAdAAIgwBFIAzBMg");
	this.shape_4.setTransform(-12.8,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A8151F").s().p("AgsBHQgHgCgEgEIAHgUIAIAGQADABAFAAQAHAAADgDQAEgEAEgHIACgHIgshoIAbAAIAdBLIAehLIAbAAIgzB4QgGAOgGAHQgKAGgOAAQgHAAgHgDg");
	this.shape_5.setTransform(-26.9,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A8151F").s().p("AAoBJIAAhjIgkBjIgHAAIgkhjIAABjIgYAAIAAiRIAhAAIAeBXIAfhXIAhAAIAACRg");
	this.shape_6.setTransform(-40.5,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.4,-15.4,100.9,30.8);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8151F").s().p("AAoBJIAAhjIgkBjIgHAAIgjhjIAABjIgZAAIAAiRIAhAAIAeBXIAfhXIAhAAIAACRg");
	this.shape.setTransform(47.5,-0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A8151F").s().p("AApBJIAAiRIAYAAIAACRgAhABJIAAiRIAZAAIAAA3IAZAAQAOABAIAGQAKAGAFAIQAFALAAAMQAAAMgFALQgFAKgKAGQgIAHgOAAgAgnAzIAWAAQAKAAAGgHQAEgGAAgLQAAgLgEgGQgGgHgKAAIgWAAg");
	this.shape_1.setTransform(31.6,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A8151F").s().p("AAaBJIAAhBIgzAAIAABBIgZAAIAAiRIAZAAIAAA8IAzAAIAAg8IAZAAIAACRg");
	this.shape_2.setTransform(17.2,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A8151F").s().p("AgtBJIAAiRIAYAAIAAA3IAYAAQAOABAKAGQAJAGAFAIQAFALAAAMQAAAMgFALQgFAKgJAGQgKAHgOAAgAgVAzIAVAAQAKAAAFgHQAGgGAAgLQAAgLgGgGQgFgHgKAAIgVAAg");
	this.shape_3.setTransform(5.4,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A8151F").s().p("Ag2A0QAEAAAEgBQAEgCADgFQADgGACgKIADgaIAIhLIBOAAIAACQIgZAAIAAh7IggAAIgEA4QgCAWgFAPQgEANgGAHQgGAIgIACQgIADgJAAg");
	this.shape_4.setTransform(-7.6,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A8151F").s().p("AAbBJIAAhgIg1BgIgXAAIAAiRIAYAAIAABeIAzheIAYAAIAACRg");
	this.shape_5.setTransform(-20.2,-0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A8151F").s().p("AgYBBQgNgJgHgRQgIgRAAgWQAAgVAIgRQAHgRANgJQAOgKAQAAQANAAAJAEQAJAFAGAHQAGAIAEAIIgVAJQgDgJgHgFQgHgGgJAAQgJAAgIAHQgHAHgFAMQgEANAAAOQAAAPAEAMQAFANAHAGQAIAHAJABQAKgBAGgGQAHgGADgJIAVAJQgEAJgGAHQgGAIgJAFQgJAFgNAAQgQAAgOgKg");
	this.shape_6.setTransform(-32.6,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#A8151F").s().p("AgYBBQgNgJgHgRQgIgRAAgWQAAgVAIgRQAHgRANgJQAOgKAQAAQANAAAJAEQAJAFAGAHQAGAIAEAIIgVAJQgDgJgHgFQgHgGgJAAQgJAAgIAHQgHAHgFAMQgEANAAAOQAAAPAEAMQAFANAHAGQAIAHAJABQAKgBAGgGQAHgGADgJIAVAJQgEAJgGAHQgGAIgJAFQgJAFgNAAQgQAAgOgKg");
	this.shape_7.setTransform(-49.3,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.4,-15.4,115,30.8);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3aXbMAAAgu1MAu2AAAMAAAAu1g");
	this.shape.setTransform(30,-50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,300,300);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#880F21").s().p("A3GEQQB7AMAygqIAUAQQhEAfg2AAQgnAAgggRgAUfEKQgBgFAFgFQARgFAIAHQgNALAAAPQgFADgEAAQgJAAACgVgAWLEXQBigFAggjQA0gkgChhQATAzgQAyQgVAtgwAUQgoAOggAAQgXAAgTgHgAsyEUQBgARBHg/QAwgsAAhnIAAjcQAAglAjAAIApAAIAAAJQg8gBgBAfIgDECQgGBihOAsQgrATgsAAQgcAAgcgIgAQOESIABmlQAAgbAbgDIAiAAQAVAFgVAKQgrgEgBAjIgGGLQgCARgEAAQgDAAgDgHgACHEVQgdgEALgJIFBAAQAWABAEgRIAohcQAHACgBATIgfBNQAAATgRAEgAmCEVQgdgEALgJIFBAAQAWABAEgRIAohcQAHACgBATIgfBNQAAATgRAEgAKNEUQgYgHAlgDICIAAIAAAKgALWC8IAAjzQALACACAPIAAD7IgBABQgGAAgGgagADvDLIAAikIBwAAQAFAMgagBIhMAAIAACGQgCAZgGAAQgDAAgEgGgAkaDLIAAikIBwAAQAFAMgagBIhMAAIAACGQgCAZgGAAQgDAAgEgGgAzaC6QBvhZgRjdQA0DDh3CAgAt9B+IAAkRIAAgDQADgaAhgBIArgCIAAAPQg+gBgCAbIAGE2IgCAAQgQAAgDgugAGlBlIAEiAIACgFQAEgKAFAcIgECDIgDACQgFAAgDgSgAhkBlIAEiAIACgFQAEgKAFAcIgECDIgDACQgFAAgDgSgA4ti+QA0h6CXAeQifgBghB8QgfBlAPCUQgviIA0iQgADugPIAAiVIB2AAQAgAAAFAKIiLAAIAABrQAAAhgMAAIgEgBgAkbgPIAAiVIB2AAQAgAAAFAKIiLAAIAABrQAAAhgMAAIgEgBgAYfgvIAAiBQAEgNAKAGIAACUQgEADgCAAQgGAAgCgPgAHNhjIAAhNQAIgKACAYIABACIAABLQgCADgCAAQgFAAgCgRgAg8hjIAAhNQAIgKACAYIABACIAABLQgCADgCAAQgFAAgCgRgAVHh3QgCgaAigTQAsgLAGAOQg2AGgQAuQgEANgDAAQgDAAgCgXgATAinQAlgkACgdQACAZgUAeQgJASgGAAQgEAAgCgIgASSjoQgagGAAgLQAWARAngPQgDAQgbAAIgFgBg");
	this.shape.setTransform(5.7,41.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiSDsIAAiYQALgGADAPQAJBgBfAUQBBAOAjgnQAkgpgbgrQgSgghRgrQhcgsgdgzQgTgyAQgnQAQglAygdQAngQAyAHIA2AUQAgAPAJggQADgLAHAIIAACVQgIANgEgQQAAgwgiggQgkgvhAADQhBASgFAxQgHAsBTAsQBJAlA6ArQAxAogKBMQgUBDhEAVQg3AVhlggQgegKgDARQgDAPgIAAIgGgCg");
	this.shape_1.setTransform(148,43.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAGBFQAVgQgEgkQgBgggPAKQgSANgUgJQgXgQAGgZQAJgeAngBQAqAMAGAqQAIAtgfAhQgLAPgEAAQgDAAgBgFg");
	this.shape_2.setTransform(125,16);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACgDbIkillIAAE7QAFAdAbAEIAbAAQADAAACACQACACAAADIAAAAQAAADgCACQgCACgDAAIiSAAQgDAAgCgCQgCgCAAgDIAAAAQAAgDACgCQACgCADAAIAaAAQAWgBAIgeIAAlhQgegpgegDQgeADAEgPIB7AAIETFUIAAkgIAAgJQgFgagagEIgaAAQgDAAgCgBQgCgDAAgDQAAgCACgDQACgCADAAICTAAQADAAACACQACADAAACQAAADgCADQgCABgDAAIgWAAQgcAEgGAZIgBAEIAAGYQgDAIgFAAQgHAAgJgNg");
	this.shape_3.setTransform(88.9,44.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AjCDkIAAgOIAgAAQAbgCAFgWIABgFIAAlzIgBgCQgFgTgZgJIgiAAIAAgLIFcAAIACBiQgKANgDgXQgEg0gpgJIiiAAIAAC0IB1AAQAHAAAFgCQAkgJAFg6IAMAAIAACfIgOAAQABg6gjgGIgEgBIiCAAIAACzQAFATATABIB+AAQAsgBAohEIAKgVIAPAAIgqByg");
	this.shape_4.setTransform(34,43.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AjCDkIAAgOIAhAAQAagCAFgWIAAgFIAAlzIAAgCQgFgTgZgJIgiAAIAAgLIFcAAIAABjQgFADgEgJQgIg6gogIIihAAIAAC0IB1AAQAGAAAGgCQAkgJAFg6IAMAAIAACfIgOAAQABg6gigGIgGgBIiBAAIAACzQAGATARABIB/AAQAsgBAohEIAKgVIAPAAIgqByg");
	this.shape_5.setTransform(-18.4,43.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ah6DEQgxgpgDhPIgDjtQADgughgMIgiAAIAAgNIDFAAIAAAMIgBABIgYAAQgrAFAAAwIAADxIABAUQANBsBqACQB/gDAKhrIAAkfQgEgYgfgDIgbAAIAAgNICfAAIAAAOQg8gFgGAvIABEIQgDA3giAoQgoArhhAIQhXgDgmgjg");
	this.shape_6.setTransform(-75,44.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AEWFnQjdgjjBh+Qg3AlhUABQhpgGhRhPQhKhHgJiHQgBhrBKhjQBKhYCCgMQBeAEBFAzQBkBWAOBzQAPCqhwBhQF7D4D2hxIAHAGQhaA7h3AAQgcAAgegDgAmdjtQgoBMAIChQAVCQBaArQBRApBYg4QBFg6ALh0QARiphMhoQgxg1hJgCQhgAGgzBXg");
	this.shape_7.setTransform(-112.1,43.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#FBF4BC","#D7C486","#A87E3D"],[0,0.486,1],-38.1,0,38.2,0).s().p("AkfEkIgYhpIAAAAIhYlsQAhgDARAzQAFACAFAEQAJAKAAANQAAAOgJAJQgKAJgMABIAjBlIAGgBQAPAAALALQAKAKAAAOQAAAPgKAKQgHAGgHADQACAMAHAHIAJAAQAPAAAKAKQAFAFAEALIAgAAIAAgBIAAgEQABgMAJgJQAJgJAKgBIAAgbIgCAAQgOAAgLgLQgKgKAAgOQAAgPAKgKQALgLAOAAIAAAAIgDh4IgRgDIAAAAQgNAAgLgKQgKgJAAgPQAAgOAKgKIAGgFQABg+AagEQAegDAPA/IAIAGQAKALAAAOQAAAOgKAJQgGAIgIACIgDABIgKAFIATB0IAFAAQAPAAAKAKQAKALAAAOQAAAOgKALQgJAIgKABIAEAdIAHgBQAOAAALALQAKAKAAAOIAAAIIAfAAIgBgIQAAgSAOgNQANgOASAAIAEABIACgfQgPgBgLgLQgMgMAAgQQAAgRAMgJQAMgMAQAAIADAAIAIiEIgKgEIgGABQgPAAgLgMQgMgKAAgRQAAgQAMgLQAGgFAHgCIAAgBQADg+AmgGQAnAGACA+IAEACQAFACAFAEQALALAAAQQAAARgLAKQgMAMgOAAIgHAAIgHACIgDABIAJCFIADgBQAQAAAMAMQAMAJAAARQAAAQgMAMQgLAMgOAAIACAfIADgBQASAAAOAOQANANAAASIgBAIIAgAAIgBgIQAAgOAKgKQALgLAOAAIAHABIAFgdQgLgBgJgIQgKgLAAgOQAAgOAKgLQALgKAOAAIAFAAIASh0IgJgFIgDgBQgIgCgHgIQgKgJABgOQgBgOAKgLIAJgGQAQg/AdADQAaAEABA+IAGAFQAKAKAAAOQAAAPgKAJQgLAKgNAAIAAAAIgSADIgCB4IABAAQANAAALALQALAKAAAPQAAAOgLAKQgLALgNAAIgCAAIgBAbQAKABAJAJQAJAJABAMIABAEIAAABIAfAAQAEgLAFgFQAKgKAPAAIAIAAQAIgHACgMQgIgDgFgGQgLgKAAgPQAAgOALgKQAKgLAOAAIAGABIAkhlQgMgBgJgJQgKgJAAgOQAAgNAKgKQAEgEAGgCQAPgzAiADIhYFsIAAAAIgXBpg");
	this.shape_8.setTransform(4.7,-50.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166.6,-79.7,333.4,159.4);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoAoQAEAAAEgDQADgEACgIQADgJACgQIAFg1IA7AAIAABoIgRAAIAAhaIgbAAIgFApQgCAUgDALQgFALgHAFQgHAFgJAAg");
	this.shape.setTransform(34.5,1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAwQgKgHgGgNQgFgMAAgQQAAgOAFgNQAFgMAKgHQAKgIALAAQAOAAAJAIQAKAHAEANQAFAMAAAOIAAAFIhDAAQABALADAIQAEAIAHAFQAGAFAIAAQAHAAAGgDQAHgEAFgGIAIAJQgGAIgJAFQgJAEgKAAQgNAAgKgHgAAagFQAAgIgCgIQgDgJgGgFQgFgGgKAAQgHAAgGAGQgGAGgDAIQgCAIgBAIIAzAAIAAAAg");
	this.shape_1.setTransform(24.8,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWBCQgKgIgFgNQgFgOAAgRQAAgZAFgQQAEgQAKgJQAKgHAPgEQANgCAEgCQAFgDAAgDIAQAAQgBAIgFAFQgFAEgHADIgQAEQgKACgIAFQgHAEgEAHQgDAGgCAKIAHgKQAFgEAGgEQAGgCAGgBQANABAJAIQAJAHAFAMQAFALAAAPQAAAPgFANQgFAMgKAIQgJAIgOAAQgNAAgJgIgAgNgPQgGAGgDAJQgDAIAAAKQAAALADAJQADAKAGAGQAGAGAHAAQAJAAAGgGQAGgGACgKQADgJAAgLQAAgKgDgIQgCgJgGgGQgGgGgJAAQgHAAgGAGg");
	this.shape_2.setTransform(14.3,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHAIQgDgDAAgFQAAgDADgEQADgDAEAAQAEAAAEADQADAEAAADQAAAFgDADQgEADgEAAQgEAAgDgDg");
	this.shape_3.setTransform(6.6,5.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAUA0IAAgvIgoAAIAAAvIgPAAIAAhoIAPAAIAAAsIAoAAIAAgsIAQAAIAABog");
	this.shape_4.setTransform(-1.1,1.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAUA0IAAhNIgoBNIgPAAIAAhoIAPAAIAABMIAohMIAQAAIAABog");
	this.shape_5.setTransform(-11.3,1.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AArA0IgegvIgGAIIAAAnIgNAAIAAgnIgHgIIgdAvIgSAAIAlg4IglgwIASAAIAkAuIAAguIANAAIAAAuIAkguIASAAIglAwIAlA4g");
	this.shape_6.setTransform(-22.9,1.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgBCIAAgbIg+AAIAAAbIgRAAIAAgoQAFAAAEgDQADgDADgIQACgIABgOIAGg3IA6AAIAABaIANAAIAAApgAgMgJQgCAMgDAKQgDAIgGAEIAuAAIAAhNIgdAAg");
	this.shape_7.setTransform(-34.8,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.2,-15.4,84.4,30.8);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(158,24,28,0)","#FF0000","rgba(175,21,43,0)"],[0,0.486,1],-298.4,-0.1,298.5,-0.1).s().p("EgunA8NMAAAh4ZMBdPAAAMAAAB4Zg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-298.4,-385.4,597,770.8);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tower();
	this.instance.setTransform(-37,-92.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37,-92.5,74,185);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgkIAVpIAAgNIABgNQAAgKgJgEIgQgGIACgFQgFAAgDgDQgBgDgBgFIACAAIgDgCIABACQgKgEgDAAIgsACQgRACgJAAIgQgHQgOgGgGgBQgTgBgZADIgBgHQAAgEACgJQADgJAAgJQAAgOgFgKIgCgDQgCgDgBgHQgEAAgBACIgCgFIgCgGIAOgfIgFgBIgBgQQAAgNAGgSIAAgNQgCgIAEgDIgBgFQgFAAgEAEQACgEAAgEIgBgIIgHgEIAQgkQAEgLABgVQAAgDAFgBIAKgCIAYADQABgRALgFQAJgDAWgDQAlgOAOgHQARgIAngKQAUgFAHgDQAOgHAAgLQAAgOgNgDQgOgEAAgDQAAgCgEgDQgFgDgCgEQgBAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABIgDAAIACgCQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBAAgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAAAQgGgJAAgFQAAgOAOgIQASgKAEgHQgCgKAGgUQAHgWAAgHIgDgIQgCgHAAgEQAAgKAOgLQAQgNADgGQgBABgBAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIADgCQAAgGgRABIgRADQgJAAgIgEQgHgDACgHQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAAAIgBAAQAEgKAUgRQAQgQAFgOIgIAAQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgCAAQAEgIADgKIAFgRQAmgBAmgbQArgfAWgEIAdgIIAAhLIAni5IAeAAIAUDVIAAAbIAlgJIgBAAIgBgHQAAgDACgDIAAgSIgdAAQALgKAIgRQAEgIASABQAFgBALgGQALgFAAgDIgBgLIgDgFQgBgBgFABIgBgQQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAABIgBAAQADgHAAgEIgMgBIgNgBIgBgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBAAAAgBQABgCAEgFIACgCIACgCIAYgEQAKgCAAgJIANgLQAOgMAGgLIANgWQAIgPgCgDQgDgMAWgNQAEgDAGgHIALgMIAcgOQATgJAFgOQAEABAGAFQAGADACAAQABAAAHgEQAGgFAFgBIAGACIAGADIgCgEIAJgBQACgBABgIQgDgDgCAAQAQgdAKgWQAEgFAlAAQAUAAASgIQASgIAMAAQAbAAAJAEIAAARIgJAOQgFAJgBAJIAIAAIAdgJIAHgIQAGgGAKAAQAXAAAkgLQASgFAsgCQAugBASgEIAJAAQABACgBAFIgBAHQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAEgBIgCAGIAEAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABIATAAQgKAMASADQAVAEAAAIQAAAGgDAJIAPAAQAHgIAKgGIAVAAIgDADQACACAFAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIAEAEIAVAAIgCgCQADACACAAQgBAFgCAAQAHADABAGIAMABIAjgBQABgBAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAEgDAKAAQAKAAAFgBIAFAHQAEAKAEABIAIAAIgCgDIALgBQAIAAAEAJIAFASQAMgBACAFQADAEAJAAQACAAAIAEQAJAFAAABIAMgCQAIAAADAEQACACABAHIgLAFQgDAEgBAIIgFAQIAEgCIAEgBIAFABIABACIAAgBIAkAIIALADIANAOIAGAAIAAACIAAgCIAAAAIgEgFIABAAIAOAFQAHAEAEAEIAJAJIgCgBQAIgCABgBQABACAFAEQAHAFAAADQgBAIgQAqIgSAoQAAAFATAJQgCAPgDAGQgEAJgLAHIAJAQQAEAHAAAIQAAAJgGAUQgIAUABAJQgBAUAYAGQAcAEAHAFIAJAAIAAgCIgBgCIACAAQAIABAAAHQAAASgEARIBVACIAGhYIgcgOIgIhMIAmgRIAAg1IAiAAIAAA4IAbAZIgLATIADAgIgeAZIAABcIAqACIAAkRIAbgTIAAhEIApgBIAAiSIA4hUIAAhGIAaimIARAAIAHDUIArBdIAACQIAugGIAABJIASAPIABACIAAEwIB5ADIAAiTIAqgxIAMh2IAPgBIgBB0IATAFIAHgnQAEgcAJgMQAGgMAFgGIAFgFIAKgWQAJgSAAgKQAAgHgRgLQgRgMAAgNQAAgMAOgiQAOgjABgDQADgPADggIAGgwQADgWAxgtQAfgdAKgVQAGgKAAgKIAAgGQgCgBgFAAQAAgDADgDIgGgGQgDgEgBgGIACgxQAAgOAbgvQAXgsAJgHQAMgJARgJQAPgIALgKQAJgHAWgCIAgAAQAJAAAMgEQALgEAAgEQBRhFBThRQB0hxBCAAQAKAAAiAJIAHAKIAJgGIAKAAQAEgBAAgDIgCgDQAdgFASgJQAMgFAfgTQAQgIAtgLQAmgIAAgDQAAgEAFABIAFADQAFghAAgIQAAgEgFgJQgDgHADgBQgaACAHgMIgdAJQgcAJgHAAQgLAAgDgDQgDgEAAgKQAAgPAbgSQAegVAFgJQAJgQAkgCIAGAEIABgEQAIgPARgbQAeg0AAgKQABgGgDgIQgIAAgGACIgKAGQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQAHgWAHgHQALgMAXAAIAQADQAOADAGAAQAAAEADAAQAFgIAJgLQALgMADgEQgRAAgXgWQgTgVAAgHQAAgEAOgWQAOgYADAAIAigCIAPAAQgCAMgCABIAOAAQAbgKAAgPQABgKAWABQAGAAABABQgBAAAAABQgBAAAAAAQAAABAAAAQAAAAAAAAIAGADQgBAIADAHQAEAHAGgBIAAgCIAAgMQAGgEALgaQAIgTAUgGIAugLQAkgJAFAAQAIAAARAHQAQAHAMAAQATAAAagYQAZgZAZABQAEAAAIACQAHADAEABQAJgBA0ghQA0gjAAgIQAAgDgQgrQAAgEADgIIAGgLIAAgVQgbgHguAAQAAgDACgFIgXgCQgNgBAAgMQAAgGAJgRQAHgRABgKQgBgGgHgMQgIgLABgMQACgUgEgdQgOAFgNgDQgQgEAAgLQAAgHANgSQALgQAKgLQAKgLADgQIAFgjIgbgCQgPgCAAAEQAAgGgcAAIgdABIABgaIADgCIgCAAIgBACIg7AiQgPAHgzgBQgFAAgFgDQgEgFAAgGIgVAAQgDAKgEABIgGgBIgCgFIgGAAQgJAAgRAGQgQAGgMAAQgLAAgFgHIAFgIIADgJQAAgDgIgIQgGgHgBgDQABgLACgFIAHgQIXjAAMAAAA0BgAuUIgIgCgCIgBgBIAAACIAAgBg");
	mask.setTransform(0.2,-1.4);

	// Слой 1
	this.instance = new lib.bg_full();
	this.instance.setTransform(-812.5,-171);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-252.1,-168,504.6,333.1);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgYYAuuMAAAhdbMAwxAAAIggIqIgDAVQgOBRgugLIgUCOIhMANIAAQvIgbAnIAABxIASAcIAAK8IgSAqIAABrIAKAMIgBdMIAMAgIAASPg");
	mask.setTransform(-0.2,-0.2);

	// Слой 1
	this.instance = new lib.bg_full();
	this.instance.setTransform(-157.5,-300);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-156.4,-299.2,312.4,598.1);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ18("synched",0);
	this.instance.setTransform(0.5,-3.3,0.826,1.504);
	this.instance.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#101010").s().p("AyuGPIAAsdMAldAAAIAAMdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-43.2,240,83.3);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 5
	this.instance = new lib.Символ13("synched",0);
	this.instance.setTransform(-148.3,-46.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-46.3,alpha:0.5},14,cjs.Ease.get(-1)).to({x:55.7,alpha:1},14,cjs.Ease.get(1)).wait(11));

	// Слой 6
	this.instance_1 = new lib.Символ14("synched",0);
	this.instance_1.setTransform(-141.3,-22.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({x:-39.3,alpha:0.5},14,cjs.Ease.get(-1)).to({x:62.7,alpha:1},14,cjs.Ease.get(1)).wait(6));

	// Слой 4
	this.instance_2 = new lib.Символ15("synched",0);
	this.instance_2.setTransform(-152.6,1.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({_off:false},0).to({x:-50.6,alpha:0.5},14,cjs.Ease.get(-1)).to({x:51.4,alpha:1},14,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-205.8,-61.6,377.3,78.9);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19("synched",0);
	this.instance.setTransform(0,0,2,2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.52,scaleY:1.52,alpha:0.48},14,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,alpha:1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-660.4,-54.6,1320.8,108.7);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8("synched",0);
	this.instance.setTransform(0,137.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:71,alpha:0.484},14,cjs.Ease.get(-1)).to({y:0,alpha:1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-166.6,57.5,333.4,159.4);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 5 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_48 = new cjs.Graphics().p("AkmM5IgHgGIgcyKIAFmIQAkhFCqgZQB6gVBlAVQCSAMAmArIASCeIATUwIAEBWQgSAoj/gGIgQABQh3AHhPAAQhzAAgWgPgAjCJnQACAwAQABIAVAAIAAiDIgnAAgAiCKYIEJgCIAAiBIkJAAgADKJ6IABgCIgBhjIgqAAIACCBIAXAAQAbAGgKgigACgH7IAqAAIgBh1IgqAAgAiCH7IEJAAIgBh1IkIAAgAjCH7IAnAAIAAh1IgmAAgACeFnIArAAIgBh+IgrAAgAiCFnIEIAAIgBh+IkHAAgAjBFnIAmAAIABh+IgmAAgACdDKIArAAIgCh3IgrAAgAiCDKIEHAAIgBh3IkHAAgAjADKIAmAAIAAh3IglAAgACbA+IArAAIgBh+IgrAAgAiDA+IEHAAIAAh+IkHAAgAi/A+IAlAAIABh+IglAAgACZhUIAsAAIgCiAIgrAAgAiDhUIEHAAIgBiAIkGAAgAi+hUIAlAAIAAiAIglAAgACYjpIArAAIgBh7IgsAAgAiDjpIEGAAIgBh7IkFAAgAi+jpIAlAAIABh7IglAAgACWl5IArAAIgBh4IAAgCQgFgLgWgCIgRAAgAiDl5IEFAAIgBiHIkEAAgAi8n3IgBB+IAlAAIAAiHIgDAAQgjADACAGgAjdp6IG+AAIAAhEIm+AAgAgHsbIgBAUIgoAhQAEAIAJAGIACABIBJAAIACgBQAPgKACgNIgwgdIAAgPIgJgBIgJABg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(48).to({graphics:mask_graphics_48,x:-176.2,y:39.6}).wait(50));

	// Слой 8
	this.instance = new lib.Символ5("synched",0);
	this.instance.setTransform(171,-59.9,1,1,-19);
	this.instance.alpha = 0.301;
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(48).to({_off:false},0).to({scaleX:1,scaleY:1,rotation:-18.8,x:-168.6,y:62.3},25,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-19,x:-508.3,y:184.5},24,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.instance_1 = new lib.Символ4("synched",0);
	this.instance_1.setTransform(-176.5,46.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(29).to({_off:false},0).to({alpha:0.48},9,cjs.Ease.get(-1)).to({alpha:1},10,cjs.Ease.get(1)).wait(50));

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(152,152,152,0)","#8C8C8C","#333333"],[0,0.165,1],0.1,169.7,0,-169.7).s().p("A9ba8MAAAg13MA63AAAMAAAA13g");
	this.shape.setTransform(127.9,-387.3,2.162,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(98));

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(152,152,152,0)","#8C8C8C","#333333"],[0,0.165,1],-263.5,0,263.6,0).s().p("EgpLAVyMAAAgrkMBSWAAAMAAAArkg");
	this.shape_1.setTransform(271.2,-159.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(98));

	// Слой 1
	this.instance_2 = new lib.bg_full();
	this.instance_2.setTransform(-533.5,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(98));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-533.5,-559.7,1068.9,859.8);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// wall
	this.instance = new lib.Символ1("synched",0);
	this.instance.setTransform(-38.4,131,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-63.4},45,cjs.Ease.get(-1)).to({x:-88.4},45,cjs.Ease.get(1)).to({_off:true},86).wait(1).to({_off:false},0).wait(273));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A9lOHIAA/2MA7LAAAMAAAAjfg");
	var mask_graphics_90 = new cjs.Graphics().p("A9lOHIAA/2MA7LAAAMAAAAjfg");
	var mask_graphics_177 = new cjs.Graphics().p("A9lOHIAA/2MA7LAAAMAAAAjfg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:233.9,y:111.4}).wait(90).to({graphics:mask_graphics_90,x:233.9,y:111.4}).wait(86).to({graphics:null,x:0,y:0}).wait(1).to({graphics:mask_graphics_177,x:233.9,y:111.4}).wait(273));

	// back_bg
	this.instance_1 = new lib.Символ2("synched",0);
	this.instance_1.setTransform(252.3,112.5,0.667,0.667);

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:306,y:112.8},45,cjs.Ease.get(-1)).to({x:359.6,y:113},45,cjs.Ease.get(1)).to({_off:true},86).wait(1).to({_off:false},0).wait(273));

	// bg
	this.instance_2 = new lib.Символ3("single",0);
	this.instance_2.setTransform(66.5,200.1,0.667,0.667);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:125.5,mode:"synched",loop:false},45,cjs.Ease.get(-1)).to({x:184.5,startPosition:45},45,cjs.Ease.get(1)).to({_off:true},86).wait(1).to({_off:false,startPosition:97},0).wait(273));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-289.1,-173.1,712.5,573.1);


// stage content:



(lib.mzvv_300x300_Queens_RTB = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// button
	this.instance = new lib.Символ20();
	this.instance.setTransform(120,200);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ20(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(450));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgdlAgBIAAipIrGAAMAAAg7qIGQAAIAAhuMBLHAAAMAAAA+KInCAAIAAB3gA1oYXMAuiAAAMAAAguiMguiAAAg");
	this.shape.setTransform(139.5,143);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(450));

	// blank
	this.instance_1 = new lib.Символ9("synched",0);
	this.instance_1.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},19,cjs.Ease.get(-1)).wait(410).to({startPosition:0},0).to({alpha:1},20,cjs.Ease.get(-1)).wait(1));

	// rulers
	this.instance_2 = new lib.Символ17("synched",0);
	this.instance_2.setTransform(174.7,276.9,1.258,0.6,0,0,0,19.6,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(450));

	// txt_rules
	this.instance_3 = new lib.Символ6();
	this.instance_3.setTransform(48.1,262.1,0.9,0.9);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;
	new cjs.ButtonHelper(this.instance_3, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(250).to({_off:false},0).to({y:240.1,alpha:0.801},20,cjs.Ease.get(1)).wait(180));

	// logo
	this.instance_4 = new lib.Символ7("synched",0,false);
	this.instance_4.setTransform(151.1,57.4,0.54,0.54);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(139).to({_off:false},0).wait(311));

	// txt1
	this.instance_5 = new lib.Символ10("synched",0,false);
	this.instance_5.setTransform(150.5,112.1,0.279,0.279);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(169).to({_off:false},0).wait(281));

	// txt2
	this.instance_6 = new lib.Символ11("synched",0,false);
	this.instance_6.setTransform(172.4,230.7,1.052,1.051);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(199).to({_off:false},0).wait(251));

	// Слой 3
	this.instance_7 = new lib.Символ21("synched",0);
	this.instance_7.setTransform(152,123.6);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(119).to({_off:false},0).to({alpha:0.238},28,cjs.Ease.get(-1)).to({alpha:0.5},30,cjs.Ease.get(1)).wait(273));

	// Слой 2
	this.instance_8 = new lib.Символ16("synched",0,false);
	this.instance_8.setTransform(0.1,-78.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(119).to({startPosition:118},0).to({y:-61.1,startPosition:146},28,cjs.Ease.get(-1)).to({y:-41.9,startPosition:177},30,cjs.Ease.get(1)).wait(273));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.1,-102.1,712.5,600.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;